version: '3'
services:
  app:
    image: kaggle/python:latest
    container_name: kaggle_container
    volumes:
      - ./src:/work
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /work
